# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
version: '3.8'

services:
  flask-service-tests:
    build:
      context: .
      dockerfile: backend/flask-service/Dockerfile
    environment:
      - FLASK_ENV=testing
      - PYTHONPATH=/app/src:/app/meeting_shared
      - TESTING="true"
      - DATABASE_URL="sqlite:///:memory:"
      - REDIS_URL="redis://redis:6379/1"
      - JWT_SECRET_KEY=test-secret-key
      - SERVICE_KEY=test-service-key
    volumes:
      - ./meeting_shared:/app/meeting_shared
      - ./backend/flask-service/src:/app/src
      - ./backend/flask-service/tests:/app/tests
    command: pytest -v tests/

  auth-service-tests:
    build:
      context: .
      dockerfile: backend/auth-service/Dockerfile
    environment:
      - FLASK_ENV=testing
      - PYTHONPATH=/app/src:/app/meeting_shared
      - TESTING="true"
      - AUTH_DATABASE_URL="sqlite:///:memory:"
      - REDIS_URL="redis://redis:6379/1"
      - JWT_SECRET_KEY=test-secret-key
      - SERVICE_KEY=test-service-key
    volumes:
      - ./meeting_shared:/app/meeting_shared
      - ./backend/auth-service/src:/app/src
      - ./backend/auth-service/tests:/app/tests
    command: pytest -v tests/

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=meetingapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d meetingapp"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: test-backend-with-apscheduler
    command: python -c "import flask; print('Flask version:', flask.__version__); import flask_wtf; print('Flask-WTF version:', flask_wtf.__version__); import apscheduler; print('APScheduler version:', apscheduler.__version__); import sys; print(sys.path)"
    volumes:
      - ./backend/flask-service:/app
      - ./backend/shared:/app/shared
    environment:
      - PYTHONPATH=/app:/app/shared
    depends_on:
      - postgres
      - redis

  websocket:
    image: node:18-slim
    command: bash -c "cd /app && npm install && npm install prom-client && node -e \"console.log('Node version:', process.version); try { require('prom-client'); console.log('prom-client is installed'); } catch(e) { console.log('Error loading prom-client:', e.message); }; console.log('Keeping container alive...'); setInterval(() => {}, 1000);\""
    volumes:
      - ./backend/node-service:/app
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://:dev-redis-123@redis:6379/0
    depends_on:
      - redis 