apiVersion: v1
kind: ConfigMap
metadata:
  name: meeting-app-config
  namespace: meeting-app
data:
  # Frontend environment variables
  NEXT_PUBLIC_API_URL: "http://localhost:30963"
  NEXT_PUBLIC_WS_URL: "ws://localhost:30283"
  NEXT_PUBLIC_BASE_URL: "http://localhost:30000"
  
  # Backend environment variables
  FLASK_ENV: "development"
  FLASK_APP: "app.py"
  API_HOST: "0.0.0.0"
  API_PORT: "5000"
  WS_HOST: "0.0.0.0"
  WS_PORT: "3001"
  
  # CORS Configuration
  CORS_ORIGINS: "http://localhost:30000,http://meeting-app.local,http://localhost:3000"
  
  # JWT Configuration
  JWT_EXPIRY_DAYS: "1"
  
  # Database configurations
  POSTGRES_DB: "meetingapp"
  POSTGRES_USER: "dev_user"
  POSTGRES_HOST: "postgres-db"
  POSTGRES_PORT: "5432"
  DATABASE_URL: "postgresql://dev_user:dev-password-123@postgres-db:5432/meetingapp"
  
  # Redis configuration
  REDIS_URL: "redis://:dev-redis-123@redis-cache:6379/0"
  REDIS_HOST: "redis-cache"
  REDIS_PORT: "6379"
  
  # Logging
  LOG_LEVEL: "debug" 