apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meeting-app-data
  namespace: meeting-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meeting-app-logs
  namespace: meeting-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path 